### ISSUE TITLE
highway=service too penalized?

### ISSUE THREAD

**Issue by hbruch** [ad-freiburg/pfaedle#29] opened 2021-06-16 08:45 UTC
We are using pfaedle with the standard `pfaedle.cfg` to calculate shapes for the [VVS GTFS feed](https://openvvs.de/dataset/gtfs-daten) ( including `-D` to recalculate all shapes).

In the resulting shapes, there is a gap between the stops at Herrenberg station (e.g. [de:08115:4512:5:B](https://www.openstreetmap.org/node/1640923838)) and the generated shapes. It looks like the service roads to pass by the actual stop might be too heavily penalized(?).

<img width="273" alt="grafik" src="https://user-images.githubusercontent.com/2187389/122187506-611f0480-ce8f-11eb-9d7e-7266417f645c.png">

I'm trying to figure out, which config change might be neeeded here and am unsure how it works exactly.

My reasoning until here:
* highway=service is not explicitly mentioned in the [bus, coach] osm_filter_keep section, but kept as they  are tagged bus=yes/psv=yes.
* Does highway=service get a lvl1+lvl4 penalty becaus it is part of osm_filter_lvl4 and at the same time (bus=yes/psv=yes) being part of osm_filter_lvl1, as I understand [EdgeCost](https://github.com/ad-freiburg/pfaedle/blob/087ea0310b7f51a5707910704de725a73f0a2629/src/pfaedle/router/Misc.h#L96-#L99)?

**Comment by Aeris1One** [comment] 2024-04-07 17:53
Can reproduce [here](https://www.openstreetmap.org/#map=17/49.39848/1.03273) with [this dataset](https://transport.data.gouv.fr/datasets/donnees-statiques-et-temps-reel-du-reseau-astuce-metropole-rouen-normandie). 

![image](https://github.com/ad-freiburg/pfaedle/assets/29739547/6e2f85fa-6eff-43be-bfaf-4a42d8d978d9)

I couldn't figure out a correct config :/

**Comment by patrickbr** [comment] 2024-04-16 21:03
> Can reproduce [here](https://www.openstreetmap.org/#map=17/49.39848/1.03273) with [this dataset](https://transport.data.gouv.fr/datasets/donnees-statiques-et-temps-reel-du-reseau-astuce-metropole-rouen-normandie). (correct road in yellow)

In your case, the problem is an incorrectly mapped roundabout here: https://www.openstreetmap.org/way/603098876

The lower part of the roundabout is mapped in the wrong direction. `junction=roundabout` is by default a one-way street, and the geometry must be mapped in the direction of travel, see [here](https://wiki.openstreetmap.org/wiki/Tag:junction=roundabout?uselang=en#The_roundabout_itself).

You can actually see this when you look at the roundabout on the rendered map, the arrow in the lower part goes in the wrong direction. Coming from the `bus=designated` road, you thus cannot enter the roundabout without entering a one-way street in the wrong direction.

You can either fix this in OSM, or lower the penalty for using a one-way street with the options `osm_one_way_speed_penalty_fac` and `osm_one_way_entry_cost`.

> I'm trying to figure out, which config change might be neeeded here and am unsure how it works exactly.

The rules are as follows:

1. Any OSM object with a matching attribute listed in `osm_filter_keep` will be kept. 
2. Then the lowest level (beginning at 0) with a matching attribute will be assigned.
3. Only *one* level is assigned to each edge.

Note that other penalties (for example, full turns, one-way streets, turn restrictions) may be present.

**Closed by patrickbr** 2024-04-16 21:03 UTC
